### ISSUE TITLE
check for $this->content should be moved higher

### ISSUE THREAD

**Issue by danmarsden** [PukunuiMalaysia/moodle-block_completedcourse#1]
https://github.com/PukunuiMalaysia/moodle-blocks_completedcourse/blob/master/block_completedcourse.php#L46

the get_content() function of a block is always called twice on a page load - for that reason we populate $this->content on the first call and then check it at the top and return the content if it isn't null - for an example see:
https://github.com/moodle/moodle/blob/master/blocks/html/block_html.php#L56

Ideally all db queries should occur after this check - eg this call:
https://github.com/PukunuiMalaysia/moodle-blocks_completedcourse/blob/master/block_completedcourse.php#L41

should really occur after the $this->content check.

**Comment by tengkualauddin** [comment]
move the check higher
